// Japanese
export * from './i18n/JA/calendar-resources';
export * from './i18n/JA/grid-resources';
export * from './i18n/JA/paginator-resources';
export * from './i18n/JA/time-picker-resources';
export * from './i18n/JA/date-range-picker-resources';
export * from './i18n/JA/carousel-resources';
export * from './i18n/JA/list-resources';
export * from './i18n/JA/resources';
// Korean
export * from './i18n/KO/calendar-resources';
export * from './i18n/KO/grid-resources';
export * from './i18n/KO/paginator-resources';
export * from './i18n/KO/time-picker-resources';
export * from './i18n/KO/date-range-picker-resources';
export * from './i18n/KO/carousel-resources';
export * from './i18n/KO/list-resources';
export * from './i18n/KO/resources';
// Spanish
export * from './i18n/ES/calendar-resources';
export * from './i18n/ES/grid-resources';
export * from './i18n/ES/paginator-resources';
export * from './i18n/ES/time-picker-resources';
export * from './i18n/ES/date-range-picker-resources';
export * from './i18n/ES/carousel-resources';
export * from './i18n/ES/list-resources';
export * from './i18n/ES/resources';
// Italian
export * from './i18n/IT/calendar-resources';
export * from './i18n/IT/grid-resources';
export * from './i18n/IT/paginator-resources';
export * from './i18n/IT/time-picker-resources';
export * from './i18n/IT/date-range-picker-resources';
export * from './i18n/IT/carousel-resources';
export * from './i18n/IT/list-resources';
export * from './i18n/IT/resources';
// Traditional Chinese (zh-Hant)
export * from './i18n/ZH-HANT/calendar-resources';
export * from './i18n/ZH-HANT/grid-resources';
export * from './i18n/ZH-HANT/paginator-resources';
export * from './i18n/ZH-HANT/time-picker-resources';
export * from './i18n/ZH-HANT/date-range-picker-resources';
export * from './i18n/ZH-HANT/carousel-resources';
export * from './i18n/ZH-HANT/list-resources';
export * from './i18n/ZH-HANT/resources';
// Simplified Chinese (zh-Hans)
export * from './i18n/ZH-HANS/calendar-resources';
export * from './i18n/ZH-HANS/grid-resources';
export * from './i18n/ZH-HANS/paginator-resources';
export * from './i18n/ZH-HANS/time-picker-resources';
export * from './i18n/ZH-HANS/date-range-picker-resources';
export * from './i18n/ZH-HANS/carousel-resources';
export * from './i18n/ZH-HANS/list-resources';
export * from './i18n/ZH-HANS/resources';
// German
export * from './i18n/DE/calendar-resources';
export * from './i18n/DE/grid-resources';
export * from './i18n/DE/paginator-resources';
export * from './i18n/DE/time-picker-resources';
export * from './i18n/DE/date-range-picker-resources';
export * from './i18n/DE/carousel-resources';
export * from './i18n/DE/list-resources';
export * from './i18n/DE/resources';
// French
export * from './i18n/FR/calendar-resources';
export * from './i18n/FR/grid-resources';
export * from './i18n/FR/paginator-resources';
export * from './i18n/FR/time-picker-resources';
export * from './i18n/FR/date-range-picker-resources';
export * from './i18n/FR/carousel-resources';
export * from './i18n/FR/list-resources';
export * from './i18n/FR/resources';
// Bulgarian
export * from './i18n/BG/calendar-resources';
export * from './i18n/BG/grid-resources';
export * from './i18n/BG/paginator-resources';
export * from './i18n/BG/time-picker-resources';
export * from './i18n/BG/date-range-picker-resources';
export * from './i18n/BG/carousel-resources';
export * from './i18n/BG/list-resources';
export * from './i18n/BG/resources';
