// Japanese
export * from './i18n/JA/calendar-resources';
export * from './i18n/JA/grid-resources';
export * from './i18n/JA/paginator-resources';
export * from './i18n/JA/time-picker-resources';
export * from './i18n/JA/date-range-picker-resources';
export * from './i18n/JA/carousel-resources';
export * from './i18n/JA/list-resources';
export * from './i18n/JA/resources';
// Korean
export * from './i18n/KO/calendar-resources';
export * from './i18n/KO/grid-resources';
export * from './i18n/KO/paginator-resources';
export * from './i18n/KO/time-picker-resources';
export * from './i18n/KO/date-range-picker-resources';
export * from './i18n/KO/carousel-resources';
export * from './i18n/KO/list-resources';
export * from './i18n/KO/resources';
// Spanish
export * from './i18n/ES/calendar-resources';
export * from './i18n/ES/grid-resources';
export * from './i18n/ES/paginator-resources';
export * from './i18n/ES/time-picker-resources';
export * from './i18n/ES/date-range-picker-resources';
export * from './i18n/ES/carousel-resources';
export * from './i18n/ES/list-resources';
export * from './i18n/ES/resources';
// Italian
export * from './i18n/IT/calendar-resources';
export * from './i18n/IT/grid-resources';
export * from './i18n/IT/paginator-resources';
export * from './i18n/IT/time-picker-resources';
export * from './i18n/IT/date-range-picker-resources';
export * from './i18n/IT/carousel-resources';
export * from './i18n/IT/list-resources';
export * from './i18n/IT/resources';
// Chinese (Taiwan) zh-tw
export * from './i18n/ZH-TW/calendar-resources';
export * from './i18n/ZH-TW/grid-resources';
export * from './i18n/ZH-TW/paginator-resources';
export * from './i18n/ZH-TW/time-picker-resources';
export * from './i18n/ZH-TW/date-range-picker-resources';
export * from './i18n/ZH-TW/carousel-resources';
export * from './i18n/ZH-TW/list-resources';
export * from './i18n/ZH-TW/resources';
// Chinese (PRC) zh-cn
export * from './i18n/ZH-CN/calendar-resources';
export * from './i18n/ZH-CN/grid-resources';
export * from './i18n/ZH-CN/paginator-resources';
export * from './i18n/ZH-CN/time-picker-resources';
export * from './i18n/ZH-CN/date-range-picker-resources';
export * from './i18n/ZH-CN/carousel-resources';
export * from './i18n/ZH-CN/list-resources';
export * from './i18n/ZH-CN/resources';
// German
export * from './i18n/DE/calendar-resources';
export * from './i18n/DE/grid-resources';
export * from './i18n/DE/paginator-resources';
export * from './i18n/DE/time-picker-resources';
export * from './i18n/DE/date-range-picker-resources';
export * from './i18n/DE/carousel-resources';
export * from './i18n/DE/list-resources';
export * from './i18n/DE/resources';
